# Generated by Django 3.2.4 on 2021-12-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomAlimento', models.CharField(help_text='nombre de los alimentos', max_length=100)),
                ('tipoAlimento', models.CharField(help_text='tipo de alimentos', max_length=100)),
                ('numCalorias', models.IntegerField(help_text='numero de calorias por porcion')),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomMascota', models.CharField(help_text='nombre de la mascota', max_length=100)),
                ('razaMascota', models.CharField(help_text='raza de la mascota', max_length=100)),
                ('edadMascota', models.IntegerField(help_text='edad de la mascota')),
                ('pesoMascota', models.CharField(help_text='peso de la mascota que', max_length=100)),
            ],
        ),
    ]
